services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys
    network_mode: bridge
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      backend:
        condition: service_started
    restart: always
    network_mode: bridge

volumes:
  db-data:
  dataprotection-keys:
